### ISSUE TITLE
Multiple Texture Slot for the Material ?

### ISSUE THREAD

**Issue by rhaamo** [codec-xyz/photo_frame_manager#1]
Hi!

Thanks for this very useful tool, I have a feature request if possible for you, I previously did manually my photo frames using the `Standard` shader but with the same picture in the `Emission Color` slot so they don't render as dark, the `Photo Frame Type` provide only one slot to be filled, would it be possible to have more to be set ?

**Comment by codec-xyz** [comment]
Okay, it is now added in v2.2.0.

**Comment by rhaamo** [comment]
working perfectly, thanks!
